env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - google
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
ignorePatterns:
  - "/dist"
plugins:
  - react
  - "@typescript-eslint"
settings: {"react": {"version": "detect"}}
rules:
  {
    semi: ["error", "always"],
    quotes: ["error", "double"],
    camelcase: 0,
    indent: "off",
  }
